AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Math Refresher API

  SAM Template for Math Refresher API
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Runtime: nodejs8.10
    CodeUri: src/
    Environment:
      Variables:
        DB_CONNECTION_STRING: ''

Resources:
  GetQuestionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: controllers/question.getQuestions
      Events:
        GetQuestion:
          Type: Api
          Properties:
            Path: /questions
            Method: get
  GetQuestionFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: controllers/question.getQuestion
      Events:
        GetQuestion:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /questions/{questionId}
            Method: get
